services:
  web:
    build: .
    ports:
      - "8010:8000"
    volumes:
      - ./whatsapp/db.sqlite3:/app/whatsapp/db.sqlite3
      - static_volume:/app/whatsapp/staticfiles
    env_file:
      - .env
    environment:
      - DEBUG=True
    restart: unless-stopped

volumes:
  static_volume:
